net/codel: Add missing #include <linux/prefetch.h>
commit ce5b4b977127ee20c3f9c3fd3637cd3796f649f5 upstream.

m68k allmodconfig:

net/sched/sch_codel.c: In function ‘dequeue’:
net/sched/sch_codel.c:70: error: implicit declaration of function ‘prefetch’
make[1]: *** [net/sched/sch_codel.o] Error 1

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Acked-by: Eric Dumazet <edumazet@google.com>
Signed-off-by: David S. Miller <davem@davemloft.net>

Gbp-Pq: Topic features/all/codel
Gbp-Pq: Name 0004-net-codel-Add-missing-include-linux-prefetch.h.patch