[PATCH] Revert "MIPS: Loongson64: Enable DMA noncoherent support"
This reverts commit 3ee7e2faef87594228eb2622f8c25c0495ea50a1.

Build for mipsel and mips64el fails to build due to missing
requisites for this commit:

	/<<PKGBUILDDIR>>/arch/mips/loongson64/env.c: In function 'prom_init_env':
	/<<PKGBUILDDIR>>/arch/mips/loongson64/env.c:138:3: error: 'dma_default_coherent' undeclared (first use in this function); did you mean 'dma_free_coherent'?
	  138 |   dma_default_coherent = true;
	      |   ^~~~~~~~~~~~~~~~~~~~
	      |   dma_free_coherent
	/<<PKGBUILDDIR>>/arch/mips/loongson64/env.c:138:3: note: each undeclared identifier is reported only once for each function it appears in
	make[6]: *** [/<<PKGBUILDDIR>>/scripts/Makefile.build:291: arch/mips/loongson64/env.o] Error 1
	make[6]: *** Waiting for unfinished jobs....

Link: https://lore.kernel.org/stable/ZZBx01WttA3R1XjI@eldamar.lan/
Signed-off-by: Salvatore Bonaccorso <carnil@debian.org>

Gbp-Pq: Topic bugfix/mips
Gbp-Pq: Name Revert-MIPS-Loongson64-Enable-DMA-noncoherent-suppor.patch